defaults:
  - _self_
  - override hydra/launcher: joblib
  # - override hydra/sweeper: optuna
  # - override hydra/sweeper/sampler: tpe


hydra:
  launcher:
    n_jobs: 1
  
  # sweeper:
  #   sampler:
  #     seed: 123
  #   direction: minimize
  #   study_name: ${mpc.wandb.group}${now:%Y%m%d-%H%M%S}
  #   storage: null
  #   n_trials: 200
  #   n_jobs: 1

  #   params:
  #     mpc.Q_q1: tag(log, interval(1e-1, 1e1))
  #     mpc.Q_q2: tag(log, interval(1e-1, 1e1))
  #     mpc.Q_dq2: tag(log, interval(1e-2, 1e1))
  #     mpc.Q_dq1: tag(log, interval(1e-2, 1e1))
  #     mpc.Qe_scaler: tag(log, interval(1.0, 5e2))
  #     mpc.R: tag(log, interval(1e0, 1e3))
  #     mpc.N: int(tag(log, interval(100, 500)))
  #     mpc.interpolate_init: choice(True, False)

mpc:
  wandb:
    enable: True
    group: "default"
  
  seed: 42
  
  # const train without adaptation
  # model_nr: 478 # const wo ball, 109057.077237
  adaptation: False

  # const train with ball
  # model_nr: 721

  # hyper
  # model_nr: 739 # with regres params

  # hd
  # model_nr: 805 # with regres params

  # res
  # model_nr: 1172

  # hyper res
  # model_nr: 1240

  # res 1917
  # model_nr: 1917


  # no ball res 1916
  # model_nr: 1916

  # no ball res hyper 
  base_model: 1916
  model_nr: 1980

  model: "hpm_drone_sim/model:v${mpc.model_nr}"

  q_e_scaler: 10.0
  dt: 0.01
  N: 160
  rope_len: 0.01 #1.0
  ball_mass: 0.5

  plot: False
  plot_save_pred: False
  render: False

  SIM_LEN: 1800
  name: ${mpc.wandb.group}${now:%Y%m%d-%H%M%S}
